yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='main_page'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts_page'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('posts/<int:post_id>', views.post_detail, name='post_detail'),
    path('posts/create', views.post_create, name='post_create'),
    path('posts/<post_id>/edit', views.post_edit, name='post_edit')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='post')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about'))
]

yatube/posts/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        'Название',
        max_length=200,
    )
    slug = models.SlugField(
        max_length=20,
        unique=True,
        verbose_name='Путь в ссылке'
    )
    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст')
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа'
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        return self.text[:settings.TEXT_SIZE_NUMBER]

yatube/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')

        def clean_text(self):
            data = self.cleaned_data['text']
            if len(data) == 0:
                raise forms.ValidationError('Тут нужно что-то написать!!!')
            return data

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect

from .forms import PostForm

from .models import Group, Post, User


def index(request):
    posts_list = Post.objects.all()
    paginator = Paginator(posts_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts_list = group.posts.all()
    paginator = Paginator(posts_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    # Здесь код запроса к модели и создание словаря контекста
    author_username = get_object_or_404(User, username=username)
    author_posts = Post.objects.filter(author=author_username)
    paginator = Paginator(author_posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'name': author_username
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = Post.objects.get(pk=post_id)
    post_count = Post.objects.filter(author=post.author).count()
    text = post.text[:30]
    context = {
        'post': post,
        'text': text,
        'post_count': post_count
    }
    return render(request, 'posts/post_detail.html', context)


def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            text = form.cleaned_data['text']
            group = form.cleaned_data['group']
            post = form.save(False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', username=request.user.username)
        return render(request, 'posts/create_post.html', {'form': form})
    form = PostForm()
    groups = Group.objects.all()
    return render(
        request,
        'posts/create_post.html',
        {
            'form': form,
            'groups': groups
        }
    )


def post_edit(request, post_id):
    post = Post.objects.get(pk=post_id)
    groups = Group.objects.all()
    is_edit = True
    if request.user.id == post.author_id:
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            text = form.cleaned_data['text']
            group = form.cleaned_data['group']
            updated_data = form.save(False)
            updated_data.author = request.user
            updated_data.save()
            post.text = text
            post.group = group
            post.save()
            return redirect('posts:profile', username=request.user.username)
        return render(
            request,
            'posts/create_post.html',
            {
                'form': form,
                'groups': groups,
                'is_edit': is_edit,
                'post': post
            }
        )
    return redirect('posts:post_detail', post_id=post.pk)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактирование поста
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {% if is_edit  %} 
                  Редактирование поста
                {% else %}
                  Новый пост
                {% endif %}         
              </div>
              <div class="card-body">        
                <form method="post" action="">
                  {% csrf_token %}

                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                      {% if is_edit %}
                        {{ post.text }}
                      {% endif %}
                    </textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Группа                  
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="" selected>---------</option>
                      {% for group in groups%}
                      <option value="{{ group.id }}">{{ group.title }}</option>
                      {% endfor %}
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Добавить
                      {% else %}
                        Сохранить
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock  %}
{% block content %}
  <div class="container py-5">
    <h1>
      Группа {{ group.title }}
    </h1>
    <p>{{ group.description|linebreaks }}</p>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>      
        <p> {{ post.text|linebreaks }}</p>
        {% if not forloop.last %}<hr>{% endif %}
      </article>
    {% endfor %}
  </div>
  {% include 'posts/includes/paginator.html' %}   
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}    
{% block title %}
  Последние обновления на сайте
{% endblock %} 
{% block content %}
  <div class="container py-5">     
    <h1>Последние обновления на сайте</h1>
      {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: 
              <a href="{% url 'posts:profile' post.author.username %}">{{ post.author.get_full_name }}</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>{{ post.text|linebreaks }}</p>    
          {% if post.group %}   
            <a href="{% url 'posts:group_posts_page' post.group.slug %}">#Группа {{ post.group.title }}</a>
          {% else %}
            <span style='color: red'>Этой публикации нет ни в одном сообществе.</span>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
        </article>
      {% endfor %}
  </div>
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}Пост {{ text }}{% endblock %}
{% block content %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}  
              <li class="list-group-item">
                Группа: {{ post.group.title }}</br>
                <a href="{% url 'posts:group_posts_page' post.group.slug %}">
                  все записи группы
                </a>
              </li>
            {% endif %}
              <li class="list-group-item">
                Автор: {{ post.author.get_full_name }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span> {{ post_count }} </span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
            {{ post.text|linebreaks }}
          </p>
        </article>
      </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{ name.get_full_name }}{% endblock %}     
{% block content %}
    <div class="container py-5">        
      <h1>Все посты пользователя {{ name.get_full_name }} </h1>
      <h3>Всего постов: {{ page_obj.paginator.count }} </h3>
      {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
          </ul>
          <p>
            {{ post.text|linebreaks }}
          </p>
          <a href="{% url 'posts:post_edit' post.pk %}">подробная информация </a></br>
               
          {% if post.group %}   
            <a href="{% url 'posts:group_posts_page' post.group.slug %}">#Группа {{ post.group.title }}</a>
          {% else %}
            <span style='color: red'>Этой публикации нет ни в одном сообществе.</span>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}        
        </article>
      {% endfor %}  
    </div>
    {% include 'posts/includes/paginator.html' %}
{% endblock %}